name: Deploy Marp to GitHub Pages
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Marp Build (Docker)
        run: |
          docker run --rm -v "${{ github.workspace }}:/home/marp/app" -e MARP_USER="$(id -u):$(id -g)" marpteam/marp-cli estres.md -o index.html

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .
          branch: gh-pages