on:
  push:
    paths:
      - 'index.md'
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Marp Build (Docker)
        run: |
          docker run --rm -v "${{ github.workspace }}:/home/marp/app" \
          -e MARP_USER="$(id -u):$(id -g)" \
          marpteam/marp-cli index.md --html -o index.html
